var players = [{num: 58, name: "Alabi, Joshua",pos: "DL", birthday: "5-Jun,295", yr: "FR", hs:"Detroit, Mich. (Cass Tech)"},
{num: 88, name: "Alexander, A.J.",pos: "TE", birthday: "2-Jun,235", yr: "FR", hs:"Burke, Va. (Lake Braddock)"},
{num: 13, name: "Apple, Eli",pos: "CB", birthday: "1-Jun,200", yr: "SO", hs:"Voorhees, N.J. (Eastern)"},
{num: 3, name: "Arnette, Damon",pos: "DB", birthday: "Jun-00,191", yr: "FR", hs:"Fort Lauderdale, Fla. (St. Thomas Aquinas)"},
{num: 4, name: "Baker, Jerome",pos: "LB", birthday: "1-Jun,215", yr: "FR", hs:"Cleveland, Ohio (St. Benedictine)"},
{num: 28, name: "Ball, Warren",pos: "RB", birthday: "1-Jun,225", yr: "JR", hs:"Columbus, Ohio (DeSales)"},
{num: 26, name: "Barnes, Jarrod",pos: "SAF", birthday: "11-May,193", yr: "JR", hs:"Westerville, Ohio (South)"},
{num: 16, name: "Barrett, J.T.",pos: "QB", birthday: "2-Jun,225", yr: "SO", hs:"Wichita Falls, Texas (Rider)"},
{num: 85, name: "Baugh, Marcus",pos: "TE", birthday: "5-Jun,255", yr: "SO", hs:"Riverside, Calif. (John W. North)"},
{num: 11, name: "Bell, Vonn",pos: "SAF", birthday: "11-May,205", yr: "JR", hs:"Rossville, Ga. (Ridgeland)"},
{num: 44, name: "Berger, Kyle",pos: "LB", birthday: "2-Jun,230", yr: "FR", hs:"Cleveland, Ohio (St. Ignatius)"},
{num: 24, name: "Berry, Rashod",pos: "TE", birthday: "4-Jun,245", yr: "FR", hs:"Lorain, Ohio (Lorain)"},
{num: 30, name: "Bogard, Devan",pos: "LB", birthday: "Jun-00,212", yr: "SR", hs:"Cleveland, Ohio (Glenville)"},
{num: 33, name: "Booker, Dante",pos: "LB", birthday: "3-Jun,233", yr: "SO", hs:"Akron (St. Vincent-St. Mary)"},
{num: 50, name: "Boren, Jacoby",pos: "OL", birthday: "2-Jun,285", yr: "SR", hs:"Pickerington, Ohio (Pickerington Central)"},
{num: 97, name: "Bosa, Joey",pos: "DL", birthday: "6-Jun,275", yr: "JR", hs:"Fort Lauderdale, Fla. (St. Thomas Aquinas)"},
{num: 76, name: "Bowen, Branden",pos: "OL", birthday: "7-Jun,320", yr: "FR", hs:"Draper, Utah (Corner Canyon)"},
{num: 80, name: "Brown, Noah",pos: "WR", birthday: "2-Jun,222", yr: "SO", hs:"Flanders, N.J. (Pope John XXIII)"},
{num: 48, name: "Burger, Joe",pos: "LB", birthday: "2-Jun,230", yr: "SR", hs:"Cincinnati, Ohio (LaSalle)"},
{num: 56, name: "Burrell, Matthew",pos: "OL", birthday: "4-Jun,300", yr: "FR", hs:"Woodbridge, Va. (Hylton)"},
{num: 10, name: "Burrow, Joe",pos: "QB", birthday: "3-Jun,208", yr: "FR", hs:"The Plains, Ohio (Athens)"},
{num: 16, name: "Burrows, Cam",pos: "DB", birthday: "Jun-00,208", yr: "JR", hs:"Trotwood, Ohio (Trotwood Madison)"},
{num: 21, name: "Campbell, Parris",pos: "WR", birthday: "1-Jun,205", yr: "FR", hs:"Akron (St. Vincent-St. Mary)"},
{num: 28, name: "Cibene, Michael",pos: "SAF", birthday: "Jun-00,185", yr: "JR", hs:"Fort Lauderdale (Pine Crest)"},
{num: 82, name: "Clark, James",pos: "WR", birthday: "10-May,185", yr: "SO", hs:"New Smyrna Beach, Fla. (New Smyrna Beach)"},
{num: 33, name: "Clutter, Austin",pos: "WR", birthday: "Jun-00,195", yr: "FR", hs:"Geneva, Ohio (Geneva)"},
{num: 13, name: "Collier, Stephen",pos: "QB", birthday: "4-Jun,225", yr: "FR", hs:"Leesburg, Ga. (Lee County)"},
{num: 8, name: "Conley, Gareon",pos: "CB", birthday: "Jun-00,195", yr: "SO", hs:"Massillon, Ohio (Washington)"},
{num: 34, name: "Conner, Nick",pos: "LB", birthday: "3-Jun,230", yr: "FR", hs:"Dublin, Ohio (Scioto)"},
{num: 11, name: "Cook, Justin",pos: "QB", birthday: "3-Jun,225", yr: "SO", hs:"Philadelphia, Pa. (Western Reserve Academy)"},
{num: 9, name: "Cornell, Jashon",pos: "DL", birthday: "3-Jun,265", yr: "FR", hs:"St. Paul, Minn. (Cretin-Derham Hall)"},
{num: 68, name: "Decker, Taylor",pos: "OL", birthday: "8-Jun,315", yr: "SR", hs:"Vandalia, Ohio (Butler)"},
{num: 5, name: "Dixon, Johnnie",pos: "WR", birthday: "11-May,194", yr: "FR", hs:"West Palm Beach, Fla. (Dwyer)"},
{num: 30, name: "Drake, Jared",pos: "LB", birthday: "Jun-00,220", yr: "SO", hs:"Westerville, Ohio (Westerville Central)"},
{num: 25, name: "Dunn, Bri'onte",pos: "RB", birthday: "Jun-00,215", yr: "JR", hs:"Canton, Ohio (GlenOak)"},
{num: 30, name: "Durbin, Tyler",pos: "K", birthday: "3-Jun,200", yr: "JR", hs:"Burke, Va. (Lake Braddock)"},
{num: 65, name: "Elflein, Pat",pos: "OL", birthday: "3-Jun,300", yr: "JR", hs:"Pickerington, Ohio (Pickerington North)"},
{num: 15, name: "Elliott, Ezekiel",pos: "RB", birthday: "Jun-00,225", yr: "JR", hs:"St. Louis, Mo. (John Burroughs)"},
{num: 38, name: "Fada, Craig",pos: "LB", birthday: "1-Jun,230", yr: "SR", hs:"Columbus, Ohio (Bishop Watterson)"},
{num: 57, name: "Farris, Chase",pos: "OL", birthday: "5-Jun,310", yr: "SR", hs:"Elyria, Ohio (Elyria)"},
{num: 77, name: "Feder, Kevin",pos: "OL", birthday: "9-Jun,305", yr: "FR", hs:"Ramsey, N.J. (Don Boscoe Prep)"},
{num: 87, name: "Ferrelli, Guy",pos: "TE", birthday: "1-Jun,245", yr: "JR", hs:"Columbus, Ohio (Bishop Ready)"},
{num: 70, name: "Fong, Chris",pos: "DE", birthday: "2-Jun,260", yr: "SR", hs:"Troy, Ohio (Troy)"},
{num: 21, name: "Forte, Trevon",pos: "CB", birthday: "8-May,175", yr: "SO", hs:"Youngstown, Ohio (Cardinal Mooney)"},
{num: 3, name: "Franklin, Khaleed",pos: "SAF", birthday: "1-Jun,215", yr: "JR", hs:"Columbus, Ohio (Beechcroft)"},
{num: 29, name: "Garris, Dominic",pos: "K", birthday: "11-May,180", yr: "SO", hs:"Lancaster, Ohio (Bloom Carroll)"},
{num: 61, name: "Gaskey, Logan",pos: "OL", birthday: "4-Jun,295", yr: "JR", hs:"Long Grove, Ill. (Adlai E. Stevenson)"},
{num: 6, name: "Gibson, Torrance",pos:"QB/WR",birthday: "4-Jun,205", yr: "FR", hs:"Plantation, Fla. (American Heritage)"},
{num: 19, name: "Glover-Williams, Eric",pos: "DB", birthday: "9-May,175", yr: "FR", hs:"Canton, Ohio (McKinley)"},
{num: 32, name: "Goins, Elijaah",pos: "SAF", birthday: "1-Jun,185", yr: "JR", hs:"Concord, N.C. (Cox Mill)"},
{num: 89, name: "Greene, Jeff",pos: "WR", birthday: "5-Jun,220", yr: "SR", hs:"Peachtree City, Ga. (Starr's Mill)"},
{num: 51, name: "Hale, Joel",pos: "OL", birthday: "4-Jun,295", yr: "SR", hs:"Greenwood, Ind. (Center Grove)"},
{num: 53, name: "Hamilton, Davon",pos: "DT",birthday: "4-Jun,300", yr: "FR", hs:"Pickerington, Ohio (Pickerington Central)"},
{num: 46, name: "Haney, Cin'Quan",pos: "DB", birthday: "1-Jun,200", yr: "JR", hs: "Dayton, Ohio (Chaminade-Julianne)"},
{num: 41, name: "Haynes, Bryce",pos: "LS", birthday: "4-Jun,225", yr: "SR", hs: "Cumming, Ga. (Pinecrest Academy)"},
{num: 14, name: "Hill, K.J.",pos: "WR", birthday: "Jun-00,195", yr: "FR", hs:  "North Little Rock, Ark. (North Little Rock)"},
{num: 77, name: "Hill, Michael",pos: "DL", birthday: "3-Jun,295", yr: "SO", hs: "Pendleton, S.C. (Pendleton)"},
{num: 47, name: "Hilliard, Justin",pos: "LB", birthday: "1-Jun,230", yr: "FR", hs: "Cincinnati, Ohio (St. Xavier)"},
{num: 10, name: "Holmes, Jalyn",pos: "DL", birthday: "5-Jun,265", yr: "SO", hs:"Norfolk, Va. (Lake Taylor)"},
{num: 24, name: "Hooker, Malik",pos: "SAF", birthday: "2-Jun,205", yr: "FR", hs:"New Castle, Pa. (New Castle)"},
{num: 15, name: "Howard, Cameron",pos: "DB", birthday: "1-Jun,203", yr: "SR", hs:"Columbus, Ohio (Gahanna Lincoln)"},
{num: 6, name: "Hubbard, Sam",pos: "DE", birthday: "5-Jun,265", yr: "FR", hs:"Cincinnati, Ohio (Archbishop Moeller)"},
{num: 35, name: "Johnson, Jeffie",pos: "RB", birthday: "10-May,197", yr: "SR", hs:"Hilliard, Ohio (Hilliard Bradley)"},
{num: 95, name: "Johnston, Cameron",pos: "P", birthday: "11-May,195", yr: "JR", hs:"Geelong, Australia (St. Josephs)"},
{num: 12, name: "Jones, Cardale",pos: "QB", birthday: "5-Jun,250", yr: "JR", hs:"Cleveland, Ohio (Glenville)"},
{num: 86, name: "Jones, Dre'Mont",pos: "DL", birthday: "3-Jun,280", yr: "FR", hs:"Cleveland, Ohio (St. Ignatius)"},
{num: 74, name: "Jones, Jamarco",pos: "OL", birthday: "5-Jun,310", yr: "SO", hs:"Chicago (De La Salle)"},
{num: 25, name: "Kelleher, Logan",pos: "DB", birthday: "10-May,195", yr: "SO", hs:"Cincinnati, Ohio (Moeller)"},
{num: 78, name: "Knox, Demetrius",pos: "OL", birthday: "4-Jun,305", yr: "FR", hs:"Fort Worth, Texas (All Saints Episcopal)"},
{num: 57, name: "Landers, Robert",pos: "DL", birthday: "1-Jun,290", yr: "FR", hs:"Dayton, Ohio (Huber Heights Wayne)"},
{num: 2, name: "Lattimore, Marshon",pos: "CB", birthday: "Jun-00,195", yr: "FR", hs:"Cleveland, Ohio (Glenville)"},
{num: 26, name: "Lawless, Michael",pos: "SAF", birthday: "Jun-00,195", yr: "JR", hs:"Dover, Ohio (Tuscarawas Central Catholic)"},
{num: 43, name: "Lee, Darron",pos: "LB", birthday: "2-Jun,235", yr: "SO", hs:"New Albany, Ohio (New Albany)"},
{num: 59, name: "Lewis, Tyquan",pos: "DL", birthday: "4-Jun,260", yr: "SO", hs:"Tarboro, N.C. (Tarboro)"},
{num: 75, name: "Lisle, Evan",pos: "OL", birthday: "7-Jun,305", yr: "SO", hs:"Centerville, Ohio (Centreville)"},
{num: 29, name: "Maduko, Mike",pos: "SAF", birthday: "8-May,188", yr: "SO", hs:"Naperville, Ill. (Montini Catholic)"},
{num: 17, name: "Marshall, Jalin",pos: "HB", birthday: "11-May,205", yr: "SO", hs:"Middletown, Ohio (Middletown)"},
{num: 42, name: "Mawhirter, Aaron",pos: "LS", birthday: "1-Jun,230", yr: "JR", hs:"Sandusky, Ohio (Perkins)"},
{num: 49, name: "McCullough, Liam",pos: "LS", birthday: "2-Jun,210", yr: "FR", hs:"Columbus, Ohio (Worthington Kilbourne)"},
{num: 20, name: "McDaniel, Devlin",pos: "WR", birthday: "11-May,195", yr: "JR", hs:"Marion, Ohio (Marion Pleasant)"},
{num: 83, name: "McLaurin, Terry",pos: "WR", birthday: "1-Jun,200", yr: "SO", hs:"Indianapolis (Cathedral)"},
{num: 5, name: "McMillan, Raekwon",pos: "LB", birthday: "2-Jun,240", yr: "SO", hs:"Hinesville, Ga. (Liberty County)"},
{num: 1, name: "Miller, Braxton",pos: "QB/HB", birthday: "2-Jun,215", yr: "SR", hs:"Huber Heights, Ohio (Wayne)"},
{num: 18, name: "Mitchell, Kato",pos: "WR", birthday: "Jun-00,190", yr: "SR", hs:"Cleveland, Ohio (John Hay)"},
{num: 44, name: "Morgan, Luke",pos: "QB", birthday: "2-Jun,235", yr: "JR", hs:"Lebanon, Ohio (Lebanon)"},
{num: 52, name: "Munger, Donovan",pos: "DL", birthday: "4-Jun,300", yr: "SO", hs:"Shaker Heights, Ohio (Shaker Heights)"},
{num: 14, name: "Norwood, Joshua",pos: "DB", birthday: "10-May,175", yr: "FR", hs:"Valdosta, Ga. (Valdosta)"},
{num: 96, name: "Nuernberger, Sean",pos: "K", birthday: "1-Jun,220", yr: "SO", hs:"Buckner, Ky. (Oldham Co.)"},
{num: 69, name: "Pahl, Brandon",pos: "OL", birthday: "2-Jun,295", yr: "FR", hs:"Cutler, Ohio (Warren)"},
{num: 91, name: "Parry, Aaron",pos: "DL", birthday: "5-Jun,275", yr: "JR", hs:"Zanesville, Ohio (Bishop Rosecrans)"},
{num: 37, name: "Perry, Joshua",pos: "LB", birthday: "4-Jun,254", yr: "SR", hs:"Galena, Ohio (Olentangy)"},
{num: 60, name: "Pfenning, Blake",pos: "OL", birthday: "5-Jun,305", yr: "FR", hs:"Wapakoneta, Ohio (Wapakoneta)"},
{num: 23, name: "Powell, Tyvis",pos: "SAF", birthday: "3-Jun,210", yr: "JR", hs:"Bedford, Ohio (Bedford)"},
{num: 54, name: "Price, Billy",pos: "OL", birthday: "4-Jun,315", yr: "SO", hs:"Austintown, Ohio (Fitch)"},
{num: 59, name: "Prince, Isiah",pos: "OL", birthday: "7-Jun,305", yr: "FR", hs:"Greenbelt, Md. (Eleanore Roosevelt)"},
{num: 19, name: "Ramstetter, Joe",pos: "WR", birthday: "3-Jun,225", yr: "JR", hs:"Cincinnati, Ohio (Elder)"},
{num: 26, name: "Reeves, Armani",pos: "CB", birthday: "10-May,198", yr: "SR", hs:"West Roxbury, Mass. (Catholic Memorial)"},
{num: 4, name: "Samuel, Curtis",pos: "RB", birthday: "11-May,200", yr: "SO", hs:"Brooklyn, N.Y. (Erasmus Hall)"},
{num: 67, name: "Schmidt, Grant",pos: "OL", birthday: "6-Jun,300", yr: "FR", hs:"Sioux Falls, S.D. (Roosevelt)"},
{num: 90, name: "Schutt, Tommy",pos: "DL", birthday: "3-Jun,290", yr: "SR", hs:"Glen Ellyn, Ill. (Glenbard West)"},
{num: 91, name: "Silverman, Philip",pos: "TE", birthday: "Jun-00,230", yr: "FR", hs:"Cincinnati, Ohio (Sycamore)"},
{num: 42, name: "Slade, Darius",pos: "DL", birthday: "4-Jun,255", yr: "FR", hs:"Montclair, N.J. (Montclair)"},
{num: 84, name: "Smith, Corey",pos: "WR", birthday: "1-Jun,195", yr: "SR", hs:"Akron, Ohio (Akron Buchtel)"},
{num: 1, name: "Smith, Erick",pos: "SAF", birthday: "Jun-00,202", yr: "SO", hs:"Cleveland, Ohio (Glenville)"},
{num: 93, name: "Sprinkle, Tracy",pos: "DL", birthday: "3-Jun,290", yr: "SO", hs:"Elyria, Ohio (Elyria)"},
{num: 87, name: "Stump, Alex",pos: "WR", birthday: "3-Jun,202", yr: "FR", hs:"Lakewood, Ohio (St. Edward)"},
{num: 20, name: "Tanner, Ron",pos: "DB", birthday: "Jun-00,205", yr: "SR", hs:"Columbus, Ohio (Eastmoor Academy)"},
{num: 79, name: "Taylor, Brady",pos: "OL", birthday: "5-Jun,300", yr: "FR", hs:"Columbus, Ohio (Bishop Ready)"},
{num: 3, name: "Thomas, Michael",pos: "WR", birthday: "3-Jun,210", yr: "JR", hs:"Los Angeles, Calif. (Woodland Hills Taft)"},
{num: 94, name: "Thompson, Dylan",pos: "DL", birthday: "5-Jun,275", yr: "FR", hs:"Lombard, Ill. (Montini Catholic)"},
{num: 71, name: "Trout, Kyle",pos: "OL", birthday: "6-Jun,310", yr: "FR", hs:"Lancaster, Ohio (Lancaster)"},
{num: 36, name: "Turnure, Zach",pos: "LB", birthday: "1-Jun,235", yr: "JR", hs:"St. Louis, Mo. (CBC)"},
{num: 81, name: "Vannett, Nick",pos: "TE", birthday: "6-Jun,260", yr: "SR", hs:"Westerville, Ohio (Central)"},
{num: 12, name: "Ward, Denzel",pos: "DB", birthday: "11-May,180", yr: "FR", hs:"Macedonia, Ohio (Nordonia)"},
{num: 92, name: "Washington, Adolphus",pos: "DL", birthday: "4-Jun,290", yr: "SR", hs:"Cincinnati, Ohio (Taft)"},
{num: 7, name: "Webb, Damon",pos: "CB", birthday: "11-May,193", yr: "SO", hs:"Detroit, Mich (Cass Tech)"},
{num: 20, name: "Weber, Mike",pos: "RB", birthday: "10-May,215", yr: "FR", hs:"Detroit, Mich. (Cass Tech)"},
{num: 55, name: "Williams, Camren",pos: "LB", birthday: "1-Jun,225", yr: "SR", hs:"West Roxbury, Mass. (Catholic Memorial)"},
{num: 98, name: "Willoughby, Jack",pos: "K", birthday: "2-Jun,210", yr: "SR", hs:"Princeton, N.J. (Lawrenceville)"},
{num: 2, name: "Wilson, Dontre",pos: "HB", birthday: "10-May,195", yr: "JR", hs:"DeSoto, Texas (DeSoto)"},
{num: 26, name: "Wise, Patrick",pos: "RB", birthday: "10-May,205", yr: "SO", hs:"Warren, Ohio (Warren G. Harding)"},
{num: 63, name: "Woidke, Kevin",pos: "OL", birthday: "6-Jun,310", yr: "FR", hs:"Cleveland, Ohio (St. Ignatius)"},
{num: 35, name: "Worley, Chris",pos: "LB", birthday: "2-Jun,225", yr: "SO", hs:"Cleveland, Ohio (Glenville)"}];